'use client';

import { useNavigate } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';
import { Container, Stack, Heading, Text } from '@marketer-pro/ui';
import { colors, space, letterSpacings } from '@marketer-pro/ui';
import { SUPPORT } from '../../lib/constants';

export default function TermsOfUsePage() {
  const navigate = useNavigate();

  const sections = [
    {
      title: 'Acceptance of Terms',
      body: `By creating an account or using Marketer-Pro Office Edition, you agree to these Terms of Use. If you do not agree, do not use the service. We may update these terms and will notify you of material changes via email or in-app notification.`,
    },
    {
      title: 'Service Description',
      body: `Marketer-Pro Office Edition is an AI-powered social media marketing platform. It uses artificial intelligence to help you create content. AI-generated content is a starting point — you are responsible for reviewing, editing, and approving all content before publishing to your social platforms.`,
    },
    {
      title: 'Acceptable Use',
      body: `You may use Marketer-Pro only for lawful marketing purposes. You may not use the service to generate spam, misinformation, hate speech, harassment, or content that violates the terms of any connected social platform. We reserve the right to terminate accounts that violate these terms.`,
    },
    {
      title: 'AI-Generated Content',
      body: `Content generated by our AI is provided as a tool to assist your marketing efforts. You retain full responsibility for any content you publish through the service. We do not guarantee the accuracy, suitability, or originality of AI-generated content. Always review content before publishing.`,
    },
    {
      title: 'Subscription and Billing',
      body: `Paid subscriptions are billed in advance on a monthly or annual basis. You may cancel at any time and your access will continue until the end of the current billing period. Refunds are available within 7 days of purchase for new subscribers. Contact ${SUPPORT.email} for billing support.`,
    },
    {
      title: 'Intellectual Property',
      body: `You retain ownership of your brand assets, prompts, and any content you create. You grant us a limited license to process your content solely to provide the service. Our platform, codebase, and AI models remain our intellectual property.`,
    },
    {
      title: 'Limitation of Liability',
      body: `To the maximum extent permitted by law, Marketer-Pro shall not be liable for any indirect, incidental, or consequential damages arising from your use of the service. Our total liability shall not exceed the amount you paid in the 12 months preceding the claim.`,
    },
    {
      title: 'Termination',
      body: `You may delete your account at any time from Settings. We may terminate or suspend your account for violations of these terms with or without notice. Upon termination, your right to use the service ceases immediately.`,
    },
    {
      title: 'Contact',
      body: `For questions about these terms, contact us at ${SUPPORT.email}.`,
    },
  ];

  return (
    <Container tabBarOffset={false}>
      <div style={{ padding: `${space[4]} ${space[5]} ${space[3]}` }}>
        <button
          onClick={() => navigate(-1)}
          aria-label="Go back"
          style={{ color: colors.text.tertiary, background: 'none', border: 'none', cursor: 'pointer', padding: 4, marginBottom: space[4] }}
        >
          <ArrowLeft size={20} />
        </button>
        <Heading level={2} gold>Terms of Use</Heading>
        <Text variant="faint" size="sm" style={{ marginTop: 6 }}>
          Last updated: June 2026
        </Text>
      </div>

      <Stack gap={20} style={{ padding: `0 ${space[5]} ${space[10]}` }}>
        <Text variant="tertiary" size="base" style={{ lineHeight: 1.7 }}>
          These Terms of Use govern your access to and use of Marketer-Pro Office Edition. Please read them carefully before using the service.
        </Text>
        {sections.map(({ title, body }) => (
          <div key={title}>
            <Text
              variant="gold"
              size="sm"
              weight="bold"
              uppercase
              style={{ letterSpacing: letterSpacings.wider, marginBottom: 10, display: 'block' }}
            >
              {title}
            </Text>
            <Text variant="tertiary" size="base" style={{ lineHeight: 1.8 }}>
              {body}
            </Text>
          </div>
        ))}
      </Stack>
    </Container>
  );
}
